"""Labware seed catalog: PLR-derived geometry shipped in the cheshire-drivers wheel.

`labware_seed.json` is generated by `scripts/regen_labware_seed.py` from
PyLabRobot's public resource catalog. A hosted deployment's labware-definition
store seeds itself from `load_labware_seed()` at boot.

The discriminated union shape keeps per-category constraints local while
letting consumers iterate a single `list[LabwareSeedEntry]` collection.
Plate entries satisfy the `_HasPlateGeometry` and `_HasWellGeometry`
protocols from `cheshire_drivers.plr.labware_converter`, so
`PLRLabwareConverter.to_plr_plate()` reconstructs a usable PLR `Plate`
directly from a `PlateSeedEntry`.
"""

from functools import lru_cache
from importlib.resources import files
from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter


class WellSeedEntry(BaseModel):
    """Per-well geometry. Satisfies `_HasWellGeometry`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    identifier: str
    row: int
    col: int
    position_x: float
    position_y: float
    position_z: float
    size_x: float
    size_y: float
    size_z: float
    max_volume: float
    bottom_type: str
    volume: float = 0.0


class PlateSeedEntry(BaseModel):
    """Plate geometry. Satisfies `_HasPlateGeometry`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    category: Literal["plate"] = "plate"
    labware_type: str
    display_name: str
    vendor: str | None = None
    plr_class_name: str | None = None
    num_rows: int
    num_cols: int
    size_x: float
    size_y: float
    size_z: float
    wells: list[WellSeedEntry]

    @property
    def name(self) -> str:
        return self.labware_type

    def well(self, identifier: str) -> WellSeedEntry:
        for w in self.wells:
            if w.identifier == identifier:
                return w
        raise KeyError(f"well {identifier!r} not in plate {self.labware_type!r}")


class TipSpotSeedEntry(BaseModel):
    """Per-tip-spot geometry."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    identifier: str
    row: int
    col: int
    position_x: float
    position_y: float
    position_z: float
    size_x: float
    size_y: float
    size_z: float
    tip_length: float
    has_filter: bool
    maximal_volume: float


class TipRackSeedEntry(BaseModel):
    """Tip rack geometry."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    category: Literal["tip_rack"] = "tip_rack"
    labware_type: str
    display_name: str
    vendor: str | None = None
    plr_class_name: str | None = None
    num_rows: int
    num_cols: int
    size_x: float
    size_y: float
    size_z: float
    tip_spots: list[TipSpotSeedEntry]


class TroughSeedEntry(BaseModel):
    """Trough (single-compartment reservoir) geometry."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    category: Literal["trough"] = "trough"
    labware_type: str
    display_name: str
    vendor: str | None = None
    plr_class_name: str
    size_x: float
    size_y: float
    size_z: float
    max_volume: float
    bottom_type: str


class TubeSeedEntry(BaseModel):
    """Tube (single-vessel) geometry."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    category: Literal["tube"] = "tube"
    labware_type: str
    display_name: str
    vendor: str | None = None
    plr_class_name: str
    size_x: float
    size_y: float
    size_z: float
    max_volume: float


class CarrierSiteSeedEntry(BaseModel):
    """Per-site geometry on a carrier."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    identifier: str
    position_x: float
    position_y: float
    position_z: float
    size_x: float
    size_y: float
    size_z: float


class CarrierSeedEntry(BaseModel):
    """Carrier (multi-site deck mount) geometry."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    category: Literal["carrier"] = "carrier"
    labware_type: str
    display_name: str
    vendor: str | None = None
    plr_class_name: str
    size_x: float
    size_y: float
    size_z: float
    sites: list[CarrierSiteSeedEntry]


LabwareSeedEntry = Annotated[
    Union[
        PlateSeedEntry,
        TipRackSeedEntry,
        TroughSeedEntry,
        TubeSeedEntry,
        CarrierSeedEntry,
    ],
    Field(discriminator="category"),
]


_SEED_LIST_ADAPTER: TypeAdapter[list[LabwareSeedEntry]] = TypeAdapter(list[LabwareSeedEntry])


def load_labware_seed() -> list[LabwareSeedEntry]:
    """Load the labware seed catalog bundled with the cheshire-drivers wheel."""
    seed_path = files("cheshire_drivers").joinpath("labware_seed.json")
    return _SEED_LIST_ADAPTER.validate_json(seed_path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _carrier_index() -> dict[str, CarrierSeedEntry]:
    return {
        entry.labware_type: entry
        for entry in load_labware_seed()
        if isinstance(entry, CarrierSeedEntry)
    }


def get_carrier_site_identifiers(catalog_ref: str) -> list[str]:
    """Site identifiers for the carrier matching catalog_ref; raises KeyError if unknown or not a carrier."""
    index = _carrier_index()
    if catalog_ref not in index:
        raise KeyError(f"Unknown carrier catalog_ref: {catalog_ref!r}")
    return [site.identifier for site in index[catalog_ref].sites]
